[package]
name = "blitz"
version = "0.1.0"
authors = ["Fabian Tamp <fabian.tamp@gmail.com>"]
edition = "2018"

[build-dependencies]
bindgen = "0.42.2"

[dependencies]
libraw-sys = "0.1.1"
libc = "0.2"
debug_stub_derive = "0.3.0"

