[package]
name = "blitzexport"
version = "0.1.0"
authors = ["Fabian Tamp <fabian.tamp@gmail.com>"]
edition = "2018"

[dependencies]
blitz = {path = "../blitz" }
libraw = {path = "../libraw" }
libc = "0.2"
image = "0.23.9"

[build-dependencies]
cbindgen = "0.14.2"

[lib]
crate-type = ["cdylib"]
