[package]
name = "libraw"
version = "0.1.0"
authors = ["Fabian Tamp <fabian.tamp@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libraw-sys = { path = "../libraw-sys" }
quick-error = "1.2.3"
